CREATE TABLE IF NOT EXISTS usuarios (
  id BIGINT  PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  username VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  rol VARCHAR(50) NOT NULL
);
CREATE TABLE IF NOT EXISTS pistas (
  id BIGINT  PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL,
  configuracion CLOB NOT NULL
);
CREATE TABLE IF NOT EXISTS bitacora (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  usuario VARCHAR(100),
  accion VARCHAR(255),
  fecha_hora TIMESTAMP
);
CREATE TABLE IF NOT EXISTS estadisticas (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  usuario VARCHAR(100),
  accion VARCHAR(100),
  exito BOOLEAN,
  fecha_hora TIMESTAMP
);
